"""empty message

Revision ID: 235d05e6abdf
Revises: 485788629ad6
Create Date: 2019-12-03 11:51:43.986131

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '235d05e6abdf'
down_revision = '485788629ad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('wall_id', sa.Integer(), nullable=False))
    op.drop_index('ix_message_timestamp', table_name='message')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'timestamp')
    op.drop_column('message', 'id')
    op.drop_column('message', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.add_column('message', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('message', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.create_index('ix_message_timestamp', 'message', ['timestamp'], unique=False)
    op.drop_column('message', 'wall_id')
    # ### end Alembic commands ###
