"""added abobout me to user

Revision ID: 337314d39e3f
Revises: 8ed53f8435f7
Create Date: 2019-10-22 09:55:29.175340

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '337314d39e3f'
down_revision = '8ed53f8435f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('about_me', sa.String(length=140), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'about_me')
    # ### end Alembic commands ###
