"""empty message

Revision ID: 4526f4f03c9f
Revises: 77890d9a3339
Create Date: 2019-12-03 11:39:35.203627

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4526f4f03c9f'
down_revision = '77890d9a3339'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'message', type_='foreignkey')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'message', 'user', ['commenter_id'], ['id'])
    # ### end Alembic commands ###
