"""empty message

Revision ID: 84cef2ad9e1e
Revises: 7b4e0313d6bc
Create Date: 2019-12-03 12:07:44.219864

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84cef2ad9e1e'
down_revision = '7b4e0313d6bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('wall_id', sa.Integer(), nullable=False))
    op.drop_index('ix_message_timestamp', table_name='message')
    op.drop_constraint(None, 'message', type_='foreignkey')
    op.drop_column('message', 'user_id')
    op.drop_column('message', 'id')
    op.drop_column('message', 'timestamp')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('message', sa.Column('timestamp', sa.DATETIME(), nullable=True))
    op.add_column('message', sa.Column('id', sa.INTEGER(), nullable=False))
    op.add_column('message', sa.Column('user_id', sa.INTEGER(), nullable=True))
    op.create_foreign_key(None, 'message', 'user', ['user_id'], ['id'])
    op.create_index('ix_message_timestamp', 'message', ['timestamp'], unique=False)
    op.drop_column('message', 'wall_id')
    # ### end Alembic commands ###
